Edit the echo in smoke-test job

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -406,14 +406,15 @@ jobs:
             # your code here
             echo " --- Cat inventory file --- "            
             export BACKEND_IP=$(cat ~/project/.circleci/ansible/inventory.txt | sed 1d)
-            echo ${BACKEND_IP}
+            echo "The BACKEND IP: ${BACKEND_IP}"
             export API_URL="http://${BACKEND_IP}:3030"
-            echo ${API_URL}            
+            echo "The API URL: ${API_URL}"
+            curl "${API_URL}/api/status"
             if curl "${API_URL}/api/status" | grep "ok"
             then
-              exit 0
+                exit 0
             else
-              exit 1
+                exit 1
             fi            
       - run:
           name: Frontend smoke test.
@@ -423,10 +424,10 @@ jobs:
             echo ${URL} 
             if curl -s ${URL} | grep "Welcome"
             then
-              # Change this to 0 after the job fails
-              exit 0
+                # Change this to 0 after the job fails
+                exit 0
             else
-              exit 1
+                exit 1
             fi
       # Here's where you will add some code to rollback on failure
       # - revert-migrations:
@@ -505,7 +506,7 @@ workflows:
           requires: [run-migrations]
       - smoke-test:
           requires: [deploy-backend, deploy-frontend]
-      - cloudfront-update:
-          requires: [smoke-test]
+      # - cloudfront-update:
+      #     requires: [smoke-test]
       # - cleanup:
       #     requires: [cloudfront-update]
